from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contin(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 387)
        Dialog.setStyleSheet("background-color:black")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(80, 40, 231, 31))
        self.name.setStyleSheet("color:#00FFF5")
        self.name.setObjectName("name")
        self.what = QtWidgets.QPushButton(Dialog)
        self.what.setGeometry(QtCore.QRect(120, 250, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.what.setFont(font)
        self.what.setStyleSheet("color:#BB7BFF")
        self.what.setObjectName("what")
        self.x5 = QtWidgets.QPushButton(Dialog)
        self.x5.setGeometry(QtCore.QRect(30, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x5.setFont(font)
        self.x5.setStyleSheet("color:#00FFF5")
        self.x5.setObjectName("x5")
        self.x6 = QtWidgets.QPushButton(Dialog)
        self.x6.setGeometry(QtCore.QRect(260, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x6.setFont(font)
        self.x6.setStyleSheet("color:#00FFF5")
        self.x6.setObjectName("x6")
        self.cont = QtWidgets.QPushButton(Dialog)
        self.cont.setGeometry(QtCore.QRect(120, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cont.setFont(font)
        self.cont.setStyleSheet("color:#00FFF5")
        self.cont.setObjectName("cont")
        self.choose = QtWidgets.QLabel(Dialog)
        self.choose.setGeometry(QtCore.QRect(110, 90, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose.setFont(font)
        self.choose.setStyleSheet("color:#BB7BFF")
        self.choose.setObjectName("choose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-style:italic;\">CuadradoSumma</span></p></body></html>"))
        self.what.setText(_translate("Dialog", "Как играть?\n*кнопка неактивна*"))
        self.x5.setText(_translate("Dialog", "Поле 5х5"))
        self.x6.setText(_translate("Dialog", "Поле 6х6"))
        self.cont.setText(_translate("Dialog", "Продолжить игру\n*кнопка неактивна*"))
        self.choose.setText(_translate("Dialog", "Выберите уровень игры:"))
