# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 378)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 371, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "Адамович А., Гранин Д."))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "Блокадная книга"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "322"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "Айтматов Ч."))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "И дольше века длится день"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "168"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "Аксенов В."))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "Звездный билет"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "609"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "Алексин А."))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "Мой брат играет на кларнете"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "558"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "Арсеньев В."))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "ДерсуУзала"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "153"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Dialog", "Астафьев В."))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Dialog", "Пастух и пастушка"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Dialog", "408"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Dialog", "Бабель И."))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Dialog", "Одесские рассказы"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Dialog", "230"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Dialog", "Бажов П."))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Dialog", "Уральские рассказы"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Dialog", "459"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Dialog", "Белых Л., Пантелеев Л."))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Dialog", "Республика ШКИД"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Dialog", "175"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Dialog", "Богомолов В."))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Dialog", "Момент истины"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Dialog", "548"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
